-- ============================================================
-- __MOD_NAME__ — Native Settings menu runtime
-- Generated by Native Settings Builder — runtime v__RUNTIME_VERSION__
--
-- Do not edit the runtime files (init.lua, modules/). To change
-- the menu, re-export from the builder: only settings.json (and
-- user_callbacks.lua, if you use callbacks) will change.
-- ============================================================

local Definition = require("modules/definition")
local Config = require("modules/config")
local Builder = require("modules/builder")
local Apply = require("modules/apply")
local SharedTab = require("modules/sharedtab")
local Lang = require("modules/lang")
local Api = require("modules/api")
local GameUI = require("modules/GameUI")

local ctx = {
    def = nil,
    values = nil,
    appliedCompat = {},
    widgets = {},
    userCallbacks = {},
    nativeSettings = nil,
    configFile = "config.json",
    logPrefix = "[NativeSettingsBuilder]",
}

-- In-game hotkey firing for keyBinding options (requires Codeware's callback system).
local function registerKeybindListeners()
    local binds = {}
    for _, opt in ipairs(ctx.def.options) do
        if opt.type == "keyBinding" and opt.apply and opt.apply.kind == "callback" then
            table.insert(binds, opt)
        end
    end
    if #binds == 0 then
        return
    end
    if not Codeware then
        print(ctx.logPrefix .. " WARN: Codeware is required for key bindings to fire in-game")
        return
    end
    local ok, err = pcall(function()
        Game.GetCallbackSystem():RegisterCallback("Input/Key", function(event)
            local key = event:GetKey().value
            local action = event:GetAction().value
            for _, opt in ipairs(binds) do
                if ctx.values[opt.id] == key then
                    if opt.isHold == true then
                        if action == "IACT_Press" then
                            Apply.dispatch(ctx, opt, true)
                        elseif action == "IACT_Release" then
                            Apply.dispatch(ctx, opt, false)
                        end
                    elseif action == "IACT_Press" then
                        Apply.dispatch(ctx, opt, true)
                    end
                end
            end
        end)
    end)
    if not ok then
        print(ctx.logPrefix .. " WARN: could not register key listener: " .. tostring(err))
    end
end

registerForEvent("onInit", function()
    local def, err = Definition.load("settings.json")
    if not def then
        print(ctx.logPrefix .. " ERROR loading settings.json: " .. tostring(err))
        return
    end
    ctx.def = def
    ctx.logPrefix = "[" .. def.mod.modName .. "]"

    ctx.nativeSettings = GetMod("nativeSettings")
    if not ctx.nativeSettings then
        print(ctx.logPrefix .. " ERROR: Native Settings Framework is not installed (required). https://www.nexusmods.com/cyberpunk2077/mods/3518")
        return
    end
    if Definition.usesVariants(def) and not Codeware then
        print(ctx.logPrefix .. " ERROR: Codeware is not installed (required for world variants). https://www.nexusmods.com/cyberpunk2077/mods/7780")
        return
    end

    -- Author callbacks are optional; a missing file is fine.
    local okCallbacks, callbacks = pcall(require, "user_callbacks")
    if okCallbacks and type(callbacks) == "table" then
        ctx.userCallbacks = callbacks
    end

    local values, appliedCompat, needsSave = Config.load(ctx.configFile, def)
    ctx.values = values
    ctx.appliedCompat = appliedCompat
    if Config.applyCompatRules(ctx) then
        needsSave = true
    end
    if needsSave then
        Config.save(ctx.configFile, def, ctx.values, ctx.appliedCompat)
    end

    Lang.init(def)

    if def.mod.tabMode == "shared" then
        SharedTab.register(ctx.nativeSettings, def.mod.sharedTab,
            Lang.get("mod.modName", def.mod.modName),
            function() Builder.buildDetail(ctx.nativeSettings, ctx) end)
    else
        Builder.buildOwnTab(ctx.nativeSettings, ctx)
    end

    registerKeybindListeners()

    -- Re-assert all world-affecting settings on every game session.
    GameUI.OnSessionStart(function()
        Apply.applyAll(ctx)
    end)
end)

-- Other mods can reach this via GetMod("<cetFolderName>").
return Api.create(ctx)
