-- user_callbacks.lua — author-written code for button presses, key bindings and
-- callback-style options. GENERATED by Native Settings Builder from the Lua
-- snippets stored in settings.json.
--
-- You may edit these function bodies directly, but re-exporting from the builder
-- will OVERWRITE this file. To keep edits safe, paste them back into the
-- builder's callback field before re-exporting.
--
-- Each function receives the option's new value (true for a button press or
-- key-down; false on key-up for hold bindings).

local M = {}

-- __CALLBACK_FUNCTIONS__

return M
